version: "3.3"
services:
    wordpress:
        container_name: wordpress
        image: wordpress:php8.1-apache
        restart: always
        stdin_open: true
        tty: true
        environment:
            WORDPRESS_DB_HOST: mariadb
            WORDPRESS_DB_USER: db_user
            WORDPRESS_DB_PASSWORD: db_user_pass
            WORDPRESS_DB_NAME: db_name
        volumes:
            - wordpress_data:/var/www/html
            - ./wordpress:/var/www/html
    mariadb:
        container_name: mariadb
        image: mariadb
        restart: always
        environment:
            MYSQL_DATABASE: db_name
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_user_pass
            MYSQL_RANDOM_ROOT_PASSWORD: 'root_pass'
        volumes:
            - db_data:/var/lib/mysql
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./certbot/conf:/etc/nginx/ssl
            - ./certbot/data:/var/www/html
    certbot:
        container_name: certbot
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/html --email gnamm.engineering@gmail.com --agree-tos --no-eff-email -d gnamm.app -d www.gnamm.app -d my.gnamm.app -d www.my.gnamm.app -d menu.gnamm.app -d www.menu.gnamm.app
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/logs:/var/log/letsencrypt
            - ./certbot/data:/var/www/html
    gnam-portal:
        image: "gnamonlinemenu/gnam-frontend-portal:0.0.1-SNAPSHOT"
        container_name: gnam-portal
        ports:
        - "3000:3000"
        environment:
        - API_INBOUND_URL=https://www.my.gnamm.app/api
        - QRCODE_BASE_URL=https://www.menu.gnamm.app
        - AUTH0_BASE_URL=https://www.my.gnamm.app
        - AUTH0_SECRET=
        - AUTH0_ISSUER_BASE_URL=
        - AUTH0_CLIENT_ID=
        - AUTH0_CLIENT_SECRET=
    gnam-client:
        image: "gnamonlinemenu/gnam-frontend-client:0.0.1-SNAPSHOT"
        container_name: gnam-client
        ports:
        - "3001:3000"
        environment:
        - API_INBOUND_URL=https://www.my.gnamm.app/api
    postgres:
        container_name: postgres
        image: 'postgres:14'
        restart: always
        environment:
        POSTGRES_USER: gnam
        POSTGRES_PASSWORD: gnam
        POSTGRES_DB: gnam
        ports:
        - "5432:5432"
    gnam-backend:
        container_name: gnam-backend
        image: 'gnamonlinemenu/gnam-backend:0.1.2'
        environment:
        - MONGODB_URI=mongodb://mongo:27017
        ports:
        - 8080:8080
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus
        command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
        expose:
        -  9090

volumes:
    db_data:
    wordpress_data:
    prometheus_data: {}