version: "3.3"
services:
    wordpress:
        container_name: wordpress
        image: wordpress:php8.1-apache
        restart: always
        stdin_open: true
        tty: true
        environment:
            WORDPRESS_DB_HOST: mariadb
            WORDPRESS_DB_USER: db_user
            WORDPRESS_DB_PASSWORD: db_user_pass
            WORDPRESS_DB_NAME: db_name
        volumes:
            - wordpress_data:/var/www/html
            - ./wordpress:/var/www/html
    mariadb:
        container_name: mariadb
        image: mariadb
        restart: always
        environment:
            MYSQL_DATABASE: db_name
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_user_pass
            MYSQL_RANDOM_ROOT_PASSWORD: 'root_pass'
        volumes:
            - db_data:/var/lib/mysql
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./certbot/conf:/etc/nginx/ssl
            - ./certbot/data:/var/www/html
    certbot:
        container_name: certbot
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/html --email gnamm.engineering@gmail.com --agree-tos --no-eff-email -d gnamm.app -d www.gnamm.app -d my.gnamm.app -d www.my.gnamm.app
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/logs:/var/log/letsencrypt
            - ./certbot/data:/var/www/html
    gnam-frontend:
        container_name: gnam-frontend
        image: 'gnamonlinemenu/gnam-frontend:0.1.0'
        ports:
            - 3000:3000
    mongo:
        container_name: mongo
        image: 'mongo:4.0'
        restart: always
        ports:
        - 27017:27017
        volumes:
        - ./mongo/volumes/mongo:/data/db
        - ./mongo/mongodump:/dump
    gnam-backend:
        container_name: gnam-backend
        image: 'gnamonlinemenu/gnam-backend:0.1.0'
        environment:
        - MONGODB_URI=mongodb://mongo:27017
        ports:
        - 8080:8080
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus
        command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
        expose:
        -  9090

volumes:
    db_data:
    wordpress_data:
    prometheus_data: {}